"""empty message

Revision ID: 057c57ed9de2
Revises: 4ea7641f8e06
Create Date: 2022-05-31 21:28:31.193861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057c57ed9de2'
down_revision = '4ea7641f8e06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('height', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'people', ['height'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'people', type_='unique')
    op.drop_column('people', 'height')
    # ### end Alembic commands ###
