"""empty message

Revision ID: 2e856d471f5d
Revises: d9bf7833c2fc
Create Date: 2022-05-31 21:56:44.783775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e856d471f5d'
down_revision = 'd9bf7833c2fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='people')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'people', ['name'], unique=False)
    # ### end Alembic commands ###
