"""empty message

Revision ID: 311dd340bcd5
Revises: 3e65977cbeb4
Create Date: 2022-05-31 21:47:11.489321

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '311dd340bcd5'
down_revision = '3e65977cbeb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('homeworld', table_name='people')
    op.drop_column('people', 'homeworld')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('homeworld', mysql.VARCHAR(length=120), nullable=False))
    op.create_index('homeworld', 'people', ['homeworld'], unique=False)
    # ### end Alembic commands ###
