"""empty message

Revision ID: 3c5b581da233
Revises: 311dd340bcd5
Create Date: 2022-05-31 21:49:37.359971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c5b581da233'
down_revision = '311dd340bcd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('homeworld', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'homeworld')
    # ### end Alembic commands ###
