"""empty message

Revision ID: 4ea7641f8e06
Revises: 95a907536367
Create Date: 2022-05-30 20:42:36.756105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ea7641f8e06'
down_revision = '95a907536367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('height', table_name='people')
    op.drop_column('people', 'height')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('height', mysql.VARCHAR(length=120), nullable=False))
    op.create_index('height', 'people', ['height'], unique=False)
    # ### end Alembic commands ###
