"""empty message

Revision ID: 95a907536367
Revises: fca7c4942578
Create Date: 2022-05-30 20:37:35.597959

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95a907536367'
down_revision = 'fca7c4942578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('homeworld', sa.String(length=120), nullable=False))
    op.add_column('people', sa.Column('created', sa.String(length=120), nullable=False))
    op.add_column('people', sa.Column('edited', sa.String(length=120), nullable=False))
    op.add_column('people', sa.Column('url', sa.String(length=120), nullable=False))
    op.add_column('people', sa.Column('_id', sa.String(length=120), nullable=True))
    op.add_column('people', sa.Column('uid', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'people', ['homeworld'])
    op.create_unique_constraint(None, 'people', ['url'])
    op.create_unique_constraint(None, 'people', ['_id'])
    op.create_unique_constraint(None, 'people', ['uid'])
    op.drop_index('description', table_name='planet')
    op.drop_column('planet', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('description', mysql.VARCHAR(length=120), nullable=True))
    op.create_index('description', 'planet', ['description'], unique=False)
    op.drop_constraint(None, 'people', type_='unique')
    op.drop_constraint(None, 'people', type_='unique')
    op.drop_constraint(None, 'people', type_='unique')
    op.drop_constraint(None, 'people', type_='unique')
    op.drop_column('people', 'uid')
    op.drop_column('people', '_id')
    op.drop_column('people', 'url')
    op.drop_column('people', 'edited')
    op.drop_column('people', 'created')
    op.drop_column('people', 'homeworld')
    # ### end Alembic commands ###
