"""empty message

Revision ID: d9bf7833c2fc
Revises: 3c5b581da233
Create Date: 2022-05-31 21:53:54.082518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9bf7833c2fc'
down_revision = '3c5b581da233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('birth_year', table_name='people')
    op.drop_index('eye_color', table_name='people')
    op.drop_index('gender', table_name='people')
    op.drop_index('hair_color', table_name='people')
    op.drop_index('height', table_name='people')
    op.drop_index('mass', table_name='people')
    op.drop_index('skin_color', table_name='people')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('skin_color', 'people', ['skin_color'], unique=False)
    op.create_index('mass', 'people', ['mass'], unique=False)
    op.create_index('height', 'people', ['height'], unique=False)
    op.create_index('hair_color', 'people', ['hair_color'], unique=False)
    op.create_index('gender', 'people', ['gender'], unique=False)
    op.create_index('eye_color', 'people', ['eye_color'], unique=False)
    op.create_index('birth_year', 'people', ['birth_year'], unique=False)
    # ### end Alembic commands ###
