"""empty message

Revision ID: fca7c4942578
Revises: 9de577b8a245
Create Date: 2022-05-27 21:22:20.598915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fca7c4942578'
down_revision = '9de577b8a245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('diameter', sa.String(length=120), nullable=False))
    op.add_column('planet', sa.Column('rotation_period', sa.String(length=120), nullable=False))
    op.add_column('planet', sa.Column('orbital_period', sa.String(length=120), nullable=False))
    op.add_column('planet', sa.Column('gravity', sa.String(length=120), nullable=False))
    op.add_column('planet', sa.Column('population', sa.String(length=120), nullable=False))
    op.add_column('planet', sa.Column('climate', sa.String(length=120), nullable=False))
    op.add_column('planet', sa.Column('terrain', sa.String(length=120), nullable=False))
    op.add_column('planet', sa.Column('surface_water', sa.String(length=120), nullable=False))
    op.add_column('planet', sa.Column('created', sa.String(length=120), nullable=False))
    op.add_column('planet', sa.Column('edited', sa.String(length=120), nullable=False))
    op.add_column('planet', sa.Column('name', sa.String(length=120), nullable=False))
    op.add_column('planet', sa.Column('url', sa.String(length=120), nullable=False))
    op.add_column('planet', sa.Column('description', sa.String(length=120), nullable=True))
    op.add_column('planet', sa.Column('_id', sa.String(length=120), nullable=True))
    op.add_column('planet', sa.Column('uid', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'planet', ['url'])
    op.create_unique_constraint(None, 'planet', ['description'])
    op.create_unique_constraint(None, 'planet', ['name'])
    op.create_unique_constraint(None, 'planet', ['_id'])
    op.create_unique_constraint(None, 'planet', ['uid'])
    op.drop_index('climate', table_name='planets')
    op.drop_index('diameter', table_name='planets')
    op.drop_index('gravity', table_name='planets')
    op.drop_index('population', table_name='planets')
    op.drop_index('rotation_period', table_name='planets')
    op.drop_index('terrain', table_name='planets')
    op.drop_column('planets', 'gravity')
    op.drop_column('planets', 'rotation_period')
    op.drop_column('planets', 'climate')
    op.drop_column('planets', 'population')
    op.drop_column('planets', 'diameter')
    op.drop_column('planets', 'terrain')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('terrain', mysql.VARCHAR(length=120), nullable=False))
    op.add_column('planets', sa.Column('diameter', mysql.VARCHAR(length=120), nullable=False))
    op.add_column('planets', sa.Column('population', mysql.VARCHAR(length=120), nullable=False))
    op.add_column('planets', sa.Column('climate', mysql.VARCHAR(length=120), nullable=False))
    op.add_column('planets', sa.Column('rotation_period', mysql.VARCHAR(length=120), nullable=False))
    op.add_column('planets', sa.Column('gravity', mysql.VARCHAR(length=120), nullable=False))
    op.create_index('terrain', 'planets', ['terrain'], unique=False)
    op.create_index('rotation_period', 'planets', ['rotation_period'], unique=False)
    op.create_index('population', 'planets', ['population'], unique=False)
    op.create_index('gravity', 'planets', ['gravity'], unique=False)
    op.create_index('diameter', 'planets', ['diameter'], unique=False)
    op.create_index('climate', 'planets', ['climate'], unique=False)
    op.drop_constraint(None, 'planet', type_='unique')
    op.drop_constraint(None, 'planet', type_='unique')
    op.drop_constraint(None, 'planet', type_='unique')
    op.drop_constraint(None, 'planet', type_='unique')
    op.drop_constraint(None, 'planet', type_='unique')
    op.drop_column('planet', 'uid')
    op.drop_column('planet', '_id')
    op.drop_column('planet', 'description')
    op.drop_column('planet', 'url')
    op.drop_column('planet', 'name')
    op.drop_column('planet', 'edited')
    op.drop_column('planet', 'created')
    op.drop_column('planet', 'surface_water')
    op.drop_column('planet', 'terrain')
    op.drop_column('planet', 'climate')
    op.drop_column('planet', 'population')
    op.drop_column('planet', 'gravity')
    op.drop_column('planet', 'orbital_period')
    op.drop_column('planet', 'rotation_period')
    op.drop_column('planet', 'diameter')
    # ### end Alembic commands ###
